### PR TITLE
Extend world generation

### PR DESCRIPTION
**Pull request by vallsv**
Hi,

I play around your project to extend a little bit the world generation.

Here is the result if you like.

Capture d’écran de 2020-05-10 13-41-29

- procedural generation of terrain
- procedural generation of clouds
- New blocks: water and snow 
- random generation of trees

I have used the lib `noise` (https://github.com/caseman/noise) for the procedural generation. It is available on pypi. I don't really like it but it does the job, and it looks like there is no easy to install equivalent.

### CODE REVIEW

**Comment by benmoran56** [comment]
Hello, and nice work! 

Is it possible to replace use of the `noise` library with a custom perlin noise generator? As much as possible we would like to avoid external modules.

**Comment by vallsv** [comment]
Hi. I recently checked the state of python libraries relative to that.

Then in your case there i feel like there is 2 good solutions:
- Use `opensimplex`. That's a single python module depending on python only, under MIT license (https://github.com/lmas/opensimplex). So it could be integrated.
- Use `perlin-numpy`. It is also a very short modules. It should be much much efficient than a pure python library. But you need a dependency to `numpy`.

I think if you expect to create something reasonably fast, and responsive, you should think about depending on  `numpy`. That's usually used for computation on arrays. In your case matrix computation is i think needed at one point (like loading only visible sectors).  But you also could use it to reduce the memory consumption.

Anyway let me know and i will update this PR.

On a side note, I have 2 comments relative to your project:
- It would be good to use `z` axis as the vertical axis (actually you use `y` as vertical). That's kind of convention.
- I think a `sector` should be a class (usually it is called a `chunk`), it would reduce a lot the computation. If you like the idea i can try. I want to use it to provide a threaded version of the generator.

Here is the current state of my experiments https://github.com/vallsv/TerraCraft/tree/extend-world-generation2.

**Comment by vallsv** [comment]
As the result is much better, i have updated the PR with a threaded version.

**Comment by benmoran56** [comment]
I had a look, and the Noise library also contains a pure python version, located here: 
https://github.com/caseman/noise/blob/master/perlin.py

I did a quick test, and it seems to work well. If we place this in /libs/ along with it's license, it would be a good alternative. At a quick glance it is missing the `octaves` option, though the SimplexNoise class does provide some initialization options which I haven't looked at closely. What do you think about going with this option? Replacing it to test is pretty straightforward:

```py
from libs import perlin

noise = perlin.SimplexNoise()

...

# noise.snoise2(x/freq, z/freq, octaves=octaves)
noise.noise2(x/freq, z/freq)
```

For your other points, switching y with z would be fine if that's something that more people would be familiar with. 
As for refactoring Sectors into Chunk classes, I would be interested to see a mockup of what you were thinking.

**Comment by vallsv** [comment]
Looks to be fine. Basically, while there is an option to initialize and save the state, i think it is fine. The octave can be easily implemented cause it is just a summation of many calls to the original generator. Could you please update your master with? So what i can use it.

For the chunk, the main idea is to provide something which group blocks together. Usually 8x8x8 blocks, usually in a dense structure (to reduce memory), usually used as leaves of an octree. Computation for hidden faces can already be done for the inside of the chunk. Adding a chunk to the world is a single operation, and you only have to check the outline blocks. So it should reduce the load of the game loop. But i did profiling and `batch.add` looks to be the bottleneck, so nothing to do with block checks i guess.

Right now i am playing with the underworld, so the amount of blocks will grow up a lot. I have created a chunk just as a block storage, but chunks them-self are not used by your model, so it still working the same as before. Here i only want to play with the generator.

**Comment by benmoran56** [comment]
Thanks, I've merged your pull request, but then replaced noise with the perlin.py linked above. Please rebase off of master. I haven't tried to account for lack of octave yet. 

The chunk idea does sound useful, if you want to work on a mock up.

Indeed, `batch.add` is the point where all data is uploaded to the GPU, so that makes sense that it's the bottleneck. One thing that could be tried is to switch to `batch.add_indexed` so that the vertex data doesn't have to be repeated. It would reduce the number of vertices per block to 8, but then you would also need to pass the index list. It's probably worth a try just to compare, but might not amount to much difference. I would say in the future, when pyglet 2.0 is out (OpenGL 3.3+), it would be worth to switch. That's because GL_QUAD will no longer be available, so the switch to GL_TRIANGLES would really cause a lot of duplicated vertex data.

**Pull request merged**
